//
//Brush Scripting
//Map: les
//Last edited by: Depro777(RU)
//

stvorka1
{
	trigger open
	{
		playsound sound/movers/doors/mrk_shutter_move5.wav
		faceangles 0 -170 0 700
	}
}

stvorka2
{
	trigger open
	{
		playsound sound/movers/doors/mrk_shutter_move5.wav
		faceangles 0 170 0 700
	}
}

photo
{
	trigger down
	{
		playsound sound/misc/bag_toss.wav
		faceangles -90 0 0 300
		trigger shkaf open
	}
}

shkaf
{
	trigger open
	{
		alertentity idiotseda

		trigger shkafclip open

		playsound sound/world/winerack.wav
		faceangles 0 -45 0 2000
		faceangles 0 -90 0 2000
	}
}

shkafclip
{
	trigger open
	{
		wait 400
		gotomarker sc_p1 600
		wait 2600
		alertentity sc_kill
	}
}

dvery_kuzova
{
	trigger open
	{
		trigger dk go
		playsound sound/scenaric/rocket/locker_open.wav
		faceangles -90 -90 0 1700
	}
}

dk
{
	trigger go
	{
		gotomarker dk_p1 100
		wait 1400
		alertentity dk_kill
	}
}

vorota1
{
	trigger open
	{
		faceangles 95 -2 -9 1700
	}
}


vorota2
{
	trigger open
	{
		faceangles 95 2 9 1700
	}
}

locker1
{
	spawn
	{
		accum 0 set 0 //  0 = closed  1 = open
	}

	trigger toggle
	{
		trigger locker1 open
		wait 5
		trigger locker1 close
	}

	trigger open
	{
		accum 0 abort_if_not_equal 0
		accum 0 set 1
		playsound sound/movers/doors/door8_open.wav
		faceangles 0 85 0 700
	}

	trigger close
	{
		accum 0 abort_if_not_equal 1
		accum 0 set 0
		playsound sound/movers/doors/door8_open.wav
		faceangles 0 0 0 700
	}
}

gramophone
{
	spawn
	{
	}

	trigger rotationg
	{
		faceangles 0 145 0 1
	}

	trigger play
	{
		playanim	0 78 looping 169260
	}
}