//
//Brush Scripting
//Map: 70
//Last edited by: Vovstein
//
radar1
{
	spawn
	{
		playsound sound/multiplayer/radar_loop02.wav looping
		faceangles 0 180 0 1000
		faceangles 0 270 0 1000
		faceangles 0 360 0 1000 
	}
	trigger rotateloop
	{
		trigger player cam1
		trigger player music
		wait 40000
		trigger player cam2
		trigger radar1 test
	}
	trigger test
	{
		wait 20000
		trigger player cam3
		trigger radar1 test2
	}
	trigger test2
	{
		wait 15000
		trigger player cam4
		trigger radar1 test3
	}
	trigger test3
	{
		wait 15000
		trigger player endmap
	}
}
radar2
{
	spawn
	{
		playsound sound/multiplayer/radar_loop02.wav looping
		trigger radar2 rotateloop 
	}

	trigger rotateloop
	{
		faceangles 0 90 0 2000
		faceangles 0 180 0 2000
		faceangles 0 270 0 2000
		faceangles 0 360 0 2000
		trigger radar2 rotateloop
	}
}
storm
{
	spawn
	{
		accum 0 set 0	// Used to count the dead.
	}
	trigger objective1
	{
		accum 0 inc 1
		accum 0 abort_if_not_equal 23
		trigger player got_objective1
	}
}	
counter1
{
	spawn
	{
		accum 2 set 0
	}
	trigger cine2
	{
		trigger bj talk
		wait 200
		trigger nazi16 go1
		wait 200
		trigger bj talk2
		wait 200
		trigger bj go1
		wait 200
		trigger player endmap2

	}
}